### ISSUE TITLE
Magic Number Exception (connecting to mcrouter)

### ISSUE THREAD

**Issue by kristianoye** [enyim/EnyimMemcached#141]
I am attempting to use the Enyim memcached client with Facebook's mcrouter.  From what I understood, mcrouter should be transparent but it isn't working out that way.  I get an InvalidOperationException (stack trace below).  The header read back from the server reads "CLIENT_ERROR malformed r" (presumably "request").  Has anyone used this client with mcrouter?  Hopefully it's just a matter of finding the right settings... (protocol issue?)

   at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.DeserializeHeader(Byte[] header, Int32& dataLength, Int32& extraLength) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\Protocol\Binary\BinaryResponse.cs:line 191
   at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.Read(PooledSocket socket) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\Protocol\Binary\BinaryResponse.cs:line 61
   at Enyim.Caching.Memcached.Protocol.Binary.StatsOperation.ReadResponse(PooledSocket socket) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\Protocol\Binary\StatsOperation.cs:line 37
   at Enyim.Caching.Memcached.Protocol.Operation.Enyim.Caching.Memcached.IOperation.ReadResponse(PooledSocket socket) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\Protocol\Operation.cs:line 27
   at Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\MemcachedNode.cs:line 525
   at Enyim.Caching.Memcached.MemcachedNode.Enyim.Caching.Memcached.IMemcachedNode.Execute(IOperation op) in e:\Projects\G99.Web.Main\Enyim.Caching\Memcached\MemcachedNode.cs:line 604
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

**Comment by kristianoye** [comment]
Nevermind... mcrouter does not appear to support binary protocol... only text.  Once I switched that in the config it appears to be working.
