### ISSUE TITLE
System.IO.IOException exception when key length is greater than 256 bytes

### ISSUE THREAD

**Issue by cw-pratik** [enyim/EnyimMemcached#170]
Hi,

Recently we received a lot of errors from memcached. 

>  MemcachedNode - System.IO.IOException: Failed to read from the socket 'xx.xx.xx.xx:11211'. Error: ?
>    at Enyim.Caching.Memcached.PooledSocket.BasicNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
>    at Enyim.Caching.Memcached.PooledSocket.Read(Byte[] buffer, Int32 offset, Int32 count)
>    at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.Read(PooledSocket socket)
>    at Enyim.Caching.Memcached.Protocol.Binary.BinarySingleItemOperation.ReadResponse(PooledSocket socket)
>    at Enyim.Caching.Memcached.Protocol.Operation.Enyim.Caching.Memcached.IOperation.ReadResponse(PooledSocket socket)
>    at Enyim.Caching.Memcached.MemcachedNode.ExecuteOperation(IOperation op)

On further investigating we came to know that the key was of greater than 500 bytes. As soon as we reduced the size of the keys the errors stop.

Will there be a fix for this or we will have to handle it from our end to make sure that the key is of a smaller size.

Am using 2.12 version of enyim memcached.

**Comment by ZhengZicong** [comment]
Memcached itself only supports keys that do not exceed 250 bytes in length

**Comment by cw-pratik** [comment]
@ZhengZicong Yes I agree memcache only allows the key to be of 250 bytes in length. 

So If by mistake someone tries to create a key of length greater than 250 bytes, an error or a warning should be thrown.

But what is happening is there are no errors. We get an `System.IO.IOException` and the enyim library thinks that the server is down. So until `deadTimeout` enyim memcache does not serve any other valid request.

The only thing I am trying to say is that the server should not be considered dead in case an invalid key is entered.

**Comment by ZhengZicong** [comment]
@cw-pratik 
Okay, maybe you're right.
Despite this, I still think that you should use the Tester-Doer mode in the application to check if the key is valid.

**Comment by ZhengZicong** [comment]
@cw-pratik 
Hey, i think we do not have to be entangled again, enyim manager version 2.16 already does not exist this problem.
The Store () method returns a boolean value that returns a false when we use a string longer than 250 bytes as the key.
Of course I keep my point of view.
